name: portfolio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  google_fonts: ^8.1.0
  font_awesome_flutter: ^11.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/profile.jpeg
    - assets/schoolline_logo.png
    - assets/schoolline_1.jpeg
    - assets/schoolline_2.jpeg
    - assets/schoolline_3.jpeg
    - assets/schoolline_4.jpeg
    - assets/schoolline_5.jpeg
    - assets/schoolline_6.jpeg
    - assets/schoolline_7.jpeg
    - assets/schoolline_8.jpeg
    - assets/schoolline_9.jpeg
    - assets/schoolline_10.jpeg
    - assets/schoolline_11.jpeg
    - assets/schoolline_12.jpeg
    - assets/schoolline_13.jpeg
    - assets/schoolline_14.jpeg
    - assets/schoolline_15.jpeg
    - assets/schoolline_16.jpeg
    - assets/schoolline_17.png
    - assets/schoolline_18.png
    - assets/schoolline_19.jpeg
    - assets/schoolline_20.jpeg
    - assets/schoolline_21.jpeg
    - assets/schoolline_22.jpeg
    - assets/schoolline_23.jpeg
    - assets/schoolline_24.jpeg
    - assets/schoolline_25.jpeg
    - assets/schoolline_26.jpeg
    - assets/schoolline_27.jpeg
    - assets/schoolline_28.jpeg
    - assets/academic_pro_logo.png
    - assets/academic_pro_1.png
    - assets/academic_pro_2.png
    - assets/academic_pro_3.png
    - assets/academic_pro_4.png
    - assets/academic_pro_5.png
    - assets/academic_pro_6.png
    - assets/academic_pro_7.png
    - assets/academic_pro_8.png
    - assets/academic_pro_9.png
    - assets/courtkeeper_logo.png
    - assets/courtkeeper_1.png
    - assets/courtkeeper_2.png
    - assets/courtkeeper_3.png
    - assets/galerie_logo.png
    - assets/galerie_1.png
    - assets/galerie_2.png
    - assets/galerie_3.png
    - assets/galerie_4.png
    - assets/galerie_5.png
    - assets/galerie_6.png
    - assets/galerie_7.png
    - assets/galerie_8.png
    - assets/galerie_9.png
    - assets/amannet_logo.png
    - assets/amannet_1.png
    - assets/amannet_2.png
    - assets/amannet_3.png
    - assets/amannet_4.png
    - assets/amannet_5.png
    - assets/amannet_6.png
    - assets/amannet_7.png
    - assets/amannet_8.png
    - assets/amannet_9.png
    - assets/amannet_10.png
    - assets/amannet_11.png
    - assets/amannet_12.png
    - assets/amannet_13.png
    - assets/amannet_14.png
    - assets/amannet_15.png
    - assets/amannet_16.png
    - assets/amannet_17.png
    - assets/amannet_18.png
    - assets/amannet_19.png
    - assets/amannet_20.png
    - assets/amannet_21.png
    - assets/amannet_22.png
    - assets/amannet_23.png
    - assets/amannet_24.png
    - assets/amannet_25.png
    - assets/calculatrice_logo.png
    - assets/calculatrice_1.jpg
    - assets/calculatrice_2.jpg
    - assets/cv kaoutar.pdf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
